use_load_balancer: true
credentials_db:
  image: my.docker.repo:5000/dotcv/credentials-db
  tag: testing
  storage_class_name: gp2
  db_name: cas
  username: root
  password_secret:
    name: cas
    key: sql-root-password
  port:
    mysql: 3306
cas:
  image: my.docker.repo:5000/dotcv/sso-webapp
  tag: testing
  hostname: my.cluster.hostname
  port:
    http: 80
    https: 443
message_validator:
  image: my.docker.repo:5000/dotcv/message-validator-webapp
  tag: testing
  hostname: my.cluster.hostname
  port:
    http: 80
    https: 443
tim_db:
  image: my.docker.repo:5000/dotcv/tim-db
  tag: testing
  storage_class_name: gp2
  db_name: cvdb
  collection_name: travelerInformation
  port:
    mongodb: 27017
whtools:
  image: my.docker.repo:5000/dotcv/whtools-webapp
  tag: testing
  system_name: "SDW 2.3"
  hostname: my.cluster.hostname
  port:
    http: 80
    https: 443
ssl:
  jetty_keystore_secret:
    name: cas
    key: jetty-keystore
  jetty_keystore_password_secret:
    name: cas
    key: jetty-keystore-password
  trust_keystore: true